workspace = { members = ["demo"] }
[package]
name = "egui_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {path="c:/work/forks/egui/crates/eframe"}
egui = {path="c:/work/forks/egui/crates/egui", features=["persistence"]}
serde = "1.0.204"
